server:
  port: 80
log:
  path: C:\\log
  level: info
spring:
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates
    mode: HTML5
  aop:
    auto: true
    proxy-target-class: true

  datasource:
    initialize: false #false时不进行数据库表结构和数据初始化
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      data:
        elasticsearch:
          cluster-name: elasticsearch #默认为elasticsearch
          cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
          properties:
            path:
              logs: ./elasticsearch/log #elasticsearch日志存储目录
              data: ./elasticsearch/data #elasticsearch数据存储目录

